name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@main
      - name: Build
        uses: TartanLlama/actions-eleventy@v1.1
        env:
          PUBLISH_DIR: _site
